---
title: "GLMs"
author: "Santiago Bianchi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

#### GLM  with Linf ####

# Packages #
```{r message=FALSE, warning=FALSE}
library(cowplot)
library(readxl)
library(plotrix)
library(readr)
library(MuMIn)
library(ggplot2)
library(dplyr)  # Data manipulation
library(tidyr)  # For pivot_longer()
```


# DATA #
```{r message=FALSE, warning=FALSE}
combined_data_1000 <- read.csv("data/combined_data_1000.csv")

str(combined_data_1000)
```

# GLMs #
```{r message=FALSE, warning=FALSE}
# Model 1: Linf ~ especies
model_Linf_1 <- glm(Linf ~ species, data = combined_data_1000, family = Gamma(link = "log"))

summary(model_Linf_1)

# Diagnostic plots
par(mfrow = c(2, 2))  # To show 4 plots with 2x2 format
plot(model_Linf_1)
```
```{r message=FALSE, warning=FALSE}
# Model 2: Linf ~ Profundidad
model_Linf_2<- glm(Linf ~  Profundidad, data = combined_data_1000, family = Gamma(link = "log"))

summary(model_Linf_2)

# Diagnostic plots
par(mfrow = c(2, 2))  # To show 4 plots with 2x2 format
plot(model_Linf_2)
```

```{r message=FALSE, warning=FALSE}
#Model 3: Linf especies + Profundidad
model_Linf_3<- glm(Linf ~  species + Profundidad, data = combined_data_1000, family = Gamma(link = "log"))

summary(model_Linf_3)

# Diagnostic plots
par(mfrow = c(2, 2))  # To show 4 plots with 2x2 format
plot(model_Linf_3)
```

```{r message=FALSE, warning=FALSE}
#Model 4: Linf especies*Profundidad
model_Linf_4<- glm(Linf ~ species*Profundidad, data = combined_data_1000, family = Gamma(link = "log"))

summary(model_Linf_4)

# Diagnostic plots
par(mfrow = c(2, 2))  # To show 4 plots with 2x2 format
plot(model_Linf_3)
```

```{r message=FALSE, warning=FALSE}
#Null model

model_Linf_null <- glm(Linf ~ 1, data = combined_data_1000, family = Gamma(link = "log"))

summary(model_Linf_null)

# Diagnostics plots for the null model
par(mfrow = c(2, 2))  # To show 4 plots with 2x2 format
plot(model_Linf_null)
```

# Comparing the candidate models #
```{r message=FALSE, warning=FALSE}
# Compare the model using model.sel
model_list <- list( Model_Linf_1 = model_Linf_1, Model_Linf_2 = model_Linf_2, Model_Linf_3 = model_Linf_3,
                    Model_Linf_4 = model_Linf_4, Model_Linf_Null = model_Linf_null)

aic_results <- model.sel(model_list)

aic_results #Model_Linf_1 is the best and Model_Linf_3 has some support

```

```{r message=FALSE, warning=FALSE}
# Model predictions
combined_data_1000$pred_model_1 <- predict(model_Linf_1, type = "response")
combined_data_1000$pred_model_2 <- predict(model_Linf_2, type = "response")
combined_data_1000$pred_model_3 <- predict(model_Linf_3, type = "response")
combined_data_1000$pred_model_4 <- predict(model_Linf_4, type = "response")
combined_data_1000$pred_model_null <- predict(model_Linf_null, type = "response")
```

```{r message=FALSE, warning=FALSE}
# pivot_longer instead gather for big data

predicciones_long <- combined_data_1000 %>%
  select(species, pred_model_1, pred_model_2, pred_model_3, pred_model_4, pred_model_null) %>%
  pivot_longer(cols = starts_with("pred_model"), names_to = "Model", values_to = "Predictions")
```

```{r message=FALSE, warning=FALSE}
# Rename the models for clarity and plotting
predicciones_long$Modelo <- recode(predicciones_long$Model, 
                                   "pred_model_1" = "Model 1: species", 
                                   "pred_model_2" = "Model 2: Profundidad", 
                                   "pred_model_3" = "Model 3: species + Profundidad", 
                                   "pred_model_4" = "Model 4: species*Profundidad", 
                                   "pred_model_nulo" = "Null Model")

# Plotting the predictions
ggplot(predicciones_long, aes(x = species, y = Predictions, fill = species)) +
  geom_boxplot() +
  facet_wrap(~ Modelo) +  # A plot for each model
  labs(title = "Species predictions", 
       x = "Species", 
       y = "Linf predictions") +
  theme_minimal() +
  theme(legend.position = "none")  
```


```{r message=FALSE, warning=FALSE}
###  GLM 1 PREDICTIONS
combined_data_1000$pred_model_1 <- predict(model_Linf_1, type = "response")

# pivot_longer instead gather for big data
predicciones_long <- combined_data_1000 %>%
  select(species, pred_model_1) %>%
  pivot_longer(cols = starts_with("pred_model"), names_to = "Model", values_to = "Predictions")

# Rename the models for clarity and plotting
predicciones_long$Model <- recode(predicciones_long$Model, 
                                   "pred_model_1" = "Model 1: species")
```

```{r message=FALSE, warning=FALSE}
# Plotting

Profundidad_label<-c("600", "", "800", "", "1000", "", "1200", "", "1400") #labels


Pred_GLM1_Linf<-ggplot(predicciones_long, aes(x = species, y = Predictions, fill = species)) +
  stat_boxplot(geom = "errorbar",
               width = 0.15) + 
  geom_boxplot() +
  ylab(bquote(L[infinity](mm)))+
  xlab("")+
  scale_y_continuous(limits = c(600, 1400), breaks = seq(600, 1400, by = 100), labels = Profundidad_label )+
  scale_x_discrete(labels = c("Atlantoraja\ncyclophora", "Bathyraja\nscaphiops\nhembras",
                              "Bathyraja\nscaphiops\nmachos", "Rioraja\nagassizii", "Zearaja\nbrevicaudata"))+
  theme_classic() +
  theme(legend.position = "none", panel.border = element_rect(fill=NA),
        axis.line = element_line(linewidth = 0.5, colour = "black",linetype = "solid"),
        axis.text.x = element_text(face= "italic", size=13,colour = "black"),                    
        axis.text.y = element_text(size=13,colour = "black"),
        axis.title.x =element_text(size=13,colour = "black", vjust = -1),       
        axis.title.y =element_text(size=rel(1),colour= "black", vjust = 1.5),   
        text = element_text(size=13),                                          
        plot.background = element_rect(color="white", fill="white", linewidth =1),    
        panel.background = element_rect(fill="white"),                         
        plot.margin = margin(t = 35,  # Top margin
                             r = 45,  # Right margin
                             b = 35,  # Bottom margin
                             l = 35)) # Left margin

Pred_GLM1_Linf

```

```{r message=FALSE, warning=FALSE}

# Model predictions based on the size (eg: total length)
combined_data_1000$pred_model_Linf <- predict(model_Linf_1, type = "response")

# Plotting
Profundidad_label<-c("600", "", "800", "", "1000", "", "1200", "", "1400")

Linfvsprof<-ggplot(combined_data_1000, aes(x = Profundidad, y = Linf, color = species)) +
  geom_point(aes(shape = species), size = 1) +  # Species
  geom_smooth(aes(linetype = species), colour = "black", method = "glm", formula = y ~ x, 
              method.args = list(family = Gamma(link = "log")), se = FALSE) +  # Species lines
  scale_color_manual(values = c(
    "R.agassizii" = "purple",
    "A.cyclophora" = "darkorange",
    "Z.brevicaudata" = "blue",
    "B. scaphiops machos" = "green4",
    "B. scaphiops hembras" = "green"
  ))+
  xlab("Profundidad (m)")+
  ylab(bquote(L[infinity](mm)))+
  scale_y_continuous(limits = c(600, 1400), breaks = seq(600, 1400, by = 100), labels = Profundidad_label )+
  scale_x_continuous(limits = c(0, 800), breaks = seq(0, 800, by = 100))+
  theme_classic() +
  theme(legend.position = "none", panel.border = element_rect(fill=NA),
        axis.line = element_line(linewidth = 0.5, colour = "black",linetype = "solid"),
        axis.text.x = element_text(size=13,colour = "black"),                   
        axis.text.y = element_text(size=13,colour = "black"),
        axis.title.x =element_text(size=13,colour = "black", vjust = -1),       
        axis.title.y =element_text(size=rel(1),colour= "black", vjust = 1.5),    
        text = element_text(size=13),                                           
        plot.background = element_rect(color="white", fill="white", linewidth =1),   
        panel.background = element_rect(fill="white"),                         
        plot.margin = margin(t = 35,  # Top margin
                             r = 45,  # Right margin
                             b = 35,  # Bottom margin
                             l = 35)) # Left margin
Linfvsprof
```

```{r message=FALSE, warning=FALSE}
# Profundidad average values
promedios_profundidad <- combined_data_1000 %>%
  group_by(species) %>%
  summarize(promedio_Profundidad = mean(Profundidad, na.rm = TRUE))

print(promedios_profundidad)

```

```{r message=FALSE, warning=FALSE}
# Min an max profundidad values
rangos_profundidad <- combined_data_1000 %>%
  group_by(species) %>%
  summarize(min_Profundidad = min(Profundidad, na.rm = TRUE),
            max_Profundidad = max(Profundidad, na.rm = TRUE))

print(rangos_profundidad)
```